<a href="https://colab.research.google.com/github/Hamna-Riaz0375/flyrankAI-internship/blob/main/work/notebooks/w01_research_question.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Research Question: Client Churn Prediction

#Student: Hamna Riaz
#Date: 2026-07-30
#Lane: Client Churn Prediction (Lane 1)

In [ ]:
# Install libraries
!pip install pandas numpy matplotlib seaborn -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("✅ All libraries imported successfully!")

✅ All libraries imported successfully!

In [ ]:
# Load data from CORRECT GitHub URL
url = 'https://raw.githubusercontent.com/flyrank-bih/flyrank-ml-internship-starter/main/data/raw/content_refresh_anonymized.csv'

try:
    df = pd.read_csv(url)
    print("✅ Data loaded successfully from GitHub!")
    print(f"📊 Shape: {df.shape}")
    print("\nFirst 5 rows:")
    display(df.head())
except Exception as e:
    print(f"⚠️ Error loading from GitHub: {e}")
    print("\n📤 Please upload the file manually:")
    from google.colab import files
    uploaded = files.upload()
    df = pd.read_csv(list(uploaded.keys())[0])
    print(f"✅ Data uploaded! Shape: {df.shape}")
    display(df.head())

✅ Data loaded successfully from GitHub!
📊 Shape: (30000, 44)

First 5 rows:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [ ]:
# === 2-3 REAL NUMBERS ===
print("="*60)
print("📊 DATA SUMMARY STATISTICS")
print("="*60)

# Number 1: Dataset size
total_rows = len(df)
total_cols = len(df.columns)
print(f"\n1️⃣ Dataset Size:")
print(f"   • Total Records: {total_rows:,}")
print(f"   • Total Features: {total_cols}")

# Number 2: Missing values
missing_count = df.isnull().sum().sum()
missing_pct = (missing_count / (total_rows * total_cols)) * 100
print(f"\n2️⃣ Data Quality:")
print(f"   • Missing Values: {missing_count:,} ({missing_pct:.2f}%)")
print(f"   • Complete Rows: {df.dropna().shape[0]:,}")

# Number 3: Column types
numeric_cols = df.select_dtypes(include=[np.number]).columns
cat_cols = df.select_dtypes(include=['object']).columns
print(f"\n3️⃣ Column Types:")
print(f"   • Numeric Columns: {len(numeric_cols)}")
print(f"   • Categorical Columns: {len(cat_cols)}")
print(f"   • Sample Numeric: {numeric_cols[:3].tolist() if len(numeric_cols)>0 else 'None'}")

print("\n" + "="*60)
print("📊 Sample Data:")
display(df.head(3))

============================================================
📊 DATA SUMMARY STATISTICS
============================================================

1️⃣ Dataset Size:
   • Total Records: 30,000
   • Total Features: 44

2️⃣ Data Quality:
   • Missing Values: 73,868 (5.60%)
   • Complete Rows: 7,350

3️⃣ Column Types:
   • Numeric Columns: 30
   • Categorical Columns: 14
   • Sample Numeric: ['search_volume', 'competition', 'cpc']

============================================================
📊 Sample Data:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9

In [ ]:
## 1. My Lane and Why

#**Chosen Lane:** Client Churn Prediction (Lane 1)

### Why This Lane?

#1. **Business Value:** Retaining clients is cheaper than acquiring new ones
#2. **Clear Action:** Account managers can proactively reach out to at-risk clients
#3. **Measurable Impact:** Success tracked through reduced churn rates
#4. **Data Availability:** Dataset contains client engagement and behavior metrics

#**Reference:** Lane 1 from `docs/ml-intern-dataset-and-lane-guide.md`

In [ ]:
## 2. The Question: Decision, Action, and Cost

### Research Question:
#**"Can we predict which clients are likely to churn in the next 30 days using their historical behavior data?"**

### The Decision:
#- Which clients should account managers contact first?

### The Action:
#- Account managers contact high-risk clients with retention offers

### Cost of Wrong Call:
#| Error Type | Cost |
#|------------|------|
#| False Positive (client wasn't leaving) | Wasted $50-100 in discounts |
#| False Negative (client left) | Lost $5,000-10,000 per client |

In [ ]:


### ✅ What I CAN claim:
#- The model can help identify clients showing early warning signs
#- Predictions can prioritize which clients to contact first

### ❌ What I CANNOT claim:
#- The model will be 100% accurate
#- This will definitely save money (needs testing)

###  What needs verification:
#- Are the features actually predictive?
#- Will account managers use the predictions?

In [ ]:
## 5. Self-Check

#- [x] Chose Client Churn Prediction lane
#- [x] Explained WHY
#- [x] Defined decision, action, and cost
#- [x] Loaded data from correct URL
#- [x] Showed 2-3 real numbers
#- [x] Careful about claims

#**✅ Ready to submit!**